import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
      <div>
        <Head>
        <title>Titus portpolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className='text-red-500'>Hey gangs</h1>
      </div>
  )
}

export default Home
